### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jsoref** [shufo/auto-assign-reviewer-by-files#111]
```
Run shufo/auto-assign-reviewer-by-files@v1.1.1
  with:
    config: .github/assign-by-files.yml
    token: ***
{
  '**/*.thrift': [ 'kgyrtkirk', 'klcopp' ],
  '**/*.g': [ 'kgyrtkirk' ],
  '**/package.jdo': [ 'kgyrtkirk' ],
  '**/schq/**': [ 'kgyrtkirk' ],
  '**/*Scheduled*': [ 'kgyrtkirk' ],
  '**/*[sS]ketches*': [ 'kgyrtkirk' ],
  Jenkinsfile: [ 'kgyrtkirk' ],
  '.github/**': [ 'kgyrtkirk' ],
  '**/ddl/**': [ 'miklosgergely' ],
  '**/ql/*@(Driver|Compiler|Executor)*.java': [ 'miklosgergely' ],
  '**/schematool/**': [ 'miklosgergely' ],
  '**/metatool/**': [ 'miklosgergely' ],
  '**/tez/**/*.java': [ 'abstractdog' ],
  '**/*Tez*java': [ 'abstractdog' ],
  '**/*TopNKey*java': [ 'kasakrisz' ],
  '**/*CardinalityPreserving*java': [ 'kasakrisz' ],
  '**/*Llap*java': [ 'pgaref' ]
}
  beeline/src/test/org/apache/hive/beeline/schematool/TestHiveSchemaTool.java matches **/schematool/**
finished!
(node:1532) UnhandledPromiseRejectionWarning: HttpError: Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the check-spelling/hive repository.
    at /home/runner/work/_actions/shufo/auto-assign-reviewer-by-files/v1.1.1/dist/index.js:1:301912
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async assignReviewers (/home/runner/work/_actions/shufo/auto-assign-reviewer-by-files/v1.1.1/dist/index.js:1:39056)
(node:1532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is from a fork of apache/hive.

The workflow is: https://github.com/apache/hive/blob/master/.github/workflows/auto-assign.yml

**Comment by shufo** [comment]
Thanks @jsoref !
Released fix as https://github.com/shufo/auto-assign-reviewer-by-files/releases/tag/v1.1.2
